### ISSUE TITLE
"FindKurentoHelpers.cmake" in CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by tfmeneses** [Telmate/TelmateFrameGrabber#6]
Hi,
When I tried compile this module I got this error:
  module/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..

> -- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
If KurentoHelpers is not found, then it is necessary to install
          kms-cmake-utils package from the kurento repository
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindKurentoHelpers.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KurentoHelpers", but CMake did not find one.
Could not find a package configuration file provided by "KurentoHelpers"
with any of the following names:
KurentoHelpersConfig.cmake
kurentohelpers-config.cmake
Add the installation prefix of "KurentoHelpers" to CMAKE_PREFIX_PATH or set
"KurentoHelpers_DIR" to a directory containing one of the above files.  If
"KurentoHelpers" provides a separate development package or SDK, be sure it
has been installed.

Can you help me?

**Comment by avis** [comment]
Hi,
It looks like you are missing kms-cmake-utils (either as a package or from sources).

**Comment by tfmeneses** [comment]
Thank you for your response!

So, I set the CMAKE_MODULE_PATH
> /module/build$ cmake .. -DCMAKE_PREFIX_PATH=/usr/local/share/cmake-3.5/Modules/ -DCMAKE_INSTALL_PREFIX=/usr/local

Now I got this error:

> If KurentoHelpers is not found, then it is necessary to install
          kms-cmake-utils package from the kurento repository
If CodeGenerator is not found, then it is necessary to install
          kms-core package from the kurento repository
-- Checking for module 'KurentoModuleCreator'
--   No package 'KurentoModuleCreator' found
CMake Error at /usr/local/share/cmake-3.5/Modules/GenericFind.cmake:131 (message):
  Library KurentoModuleCreator not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.5/Modules/CodeGenerator.cmake:5 (generic_find)
  CMakeLists.txt:14 (include)

I've the kurento-module-creator in /usr/bin

Regards

**Comment by avis** [comment]
You may be missing or have the wrong path for FindKurentoModuleCreator.cmake, make sure your cmake can find it.
I'd say try to compile the kurento sample module first to make sure your environment is kurento module ready....

**Comment by tfmeneses** [comment]
Thank you!

Before I make the kurento from source and really maybe wrong something.

Now I installed from apt-get and I got this error:


> [ 57%] Linking CXX shared library libkmstelmateframegrabberimpl.so
/usr/bin/ld: libkmstelmateframegrabberinterface.a(TelmateFrameGrabberInternal.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
libkmstelmateframegrabberinterface.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/server/CMakeFiles/kmstelmateframegrabberimpl.dir/build.make:195: recipe for target 'src/server/libkmstelmateframegrabberimpl.so.0.0.1~0.g429925a' failed
make[2]: *** [src/server/libkmstelmateframegrabberimpl.so.0.0.1~0.g429925a] Error 1
CMakeFiles/Makefile2:216: recipe for target 'src/server/CMakeFiles/kmstelmateframegrabberimpl.dir/all' failed
make[1]: *** [src/server/CMakeFiles/kmstelmateframegrabberimpl.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by avis** [comment]
You seem to have a pie issue, maybe KMS was compiled with pie but your compiler defaults to no pie.
Try adding -fPIC to CMAKE_CXX_FLAGS in CMakeLists.txt

**Comment by tfmeneses** [comment]
Perfect.

Thank you so much!

**Comment by javadasoodeh** [comment]
i followed above step but occurred an error:
1 - use cmake for current directory 
`cmake . -DCMAKE_PREFIX_PATH=/cygdrive/c/cygwin64/usr/local/share/ -DCMAKE_MODULE_PATH=/cygdrive/c/cygwin64/usr/local/share/cmake-3.18/Modules/ -DCMAKE_INSTALL_PREFIX=/cygdrive/c/cygwin64/usr/local`

then error: 

```
CMake Warning at /usr/local/share/cmake-3.18.0/Modules/Platform/CYGWIN.cmake:15 (message):
  CMake no longer defines WIN32 on Cygwin!

  (1) If you are just trying to build this project, ignore this warning or
  quiet it by setting CMAKE_LEGACY_CYGWIN_WIN32=0 in your environment or in
  the CMake cache.  If later configuration or build errors occur then this
  project may have been written under the assumption that Cygwin is WIN32.
  In that case, set CMAKE_LEGACY_CYGWIN_WIN32=1 instead.

  (2) If you are developing this project, add the line

    set(CMAKE_LEGACY_CYGWIN_WIN32 0) # Remove when CMake >= 2.8.4 is required

  at the top of your top-level CMakeLists.txt file or set the minimum
  required version of CMake to 2.8.4 or higher.  Then teach your project to
  build on Cygwin without WIN32.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18.0/Modules/CMakeSystemSpecificInformation.cmake:26 (include)
  CMakeLists.txt:3 (project)


If KurentoHelpers is not found, then it is necessary to install
          kms-cmake-utils package from the kurento repository
-- Found KurentoHelpers: 6.14.1-dev (found version "6.14.1-dev")
-- Found Git: /cygdrive/c/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
-- No version info from git. Using default: 5.1.4-dev
-- Compiling kurento-media-server-5.1.4-dev
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3")
CMake Error at /usr/local/share/cmake-3.18.0/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system filesystem
  program_options unit_test_framework)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18.0/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.18.0/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  /cygdrive/c/cygwin64/usr/local/share/cmake-3.18/Modules/GenericFind.cmake:105 (find_package)
  CMakeLists.txt:35 (generic_find)


-- Configuring incomplete, errors occurred!
See also "/cygdrive/c/Users/Javad/Downloads/kurento-media-server-release-5.1/kurento-media-server-release-5.1/CMakeFiles/CMakeOutput.log".

```
2 - i installed kms-cmake-utils
```
cmake .
make 
make install
```
3 - next repeat number 1 but the error repeated for me same number 1 error 
 **can you help me what to do ?**
